name: CI/CD Pluralsight Course Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
      
      - id: build
        name: Build
        run: dotnet build --no-restore
        
      - id: test
        name: Test
        run: dotnet test --no-build --verbosity normal
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Deploy to GitHub Pages
        run: |
          DEPLOYMENT_KEY="${{ secrets.TEST_DEPLOYMENT_KEY }}"
          echo "Simulating deployment with key: $DEPLOYMENT_KEY"
          echo "Deployment simulation successful!"
        